Refactored starting the Elevation server.

diff --git a/project/server/res/scripts/start b/project/server/res/scripts/start
--- a/project/server/res/scripts/start
+++ b/project/server/res/scripts/start
@@ -7,7 +7,7 @@ source "${SCRIPTS_DIR}/common" # Add the functions in 'common'
 # EXPECTED PARAMS:
 # 1 : The process to check the existance of.
 # Return code : 0 if the process already started, otherwise nonzero.
-hasProcessStarted() {
+isProcessRunning() {
     checkParamNum 1 $# || exit 1
     local PROCESS_NAME="${1}"
     pidof "${PROCESS_NAME}" >/dev/null
@@ -16,7 +16,7 @@ hasProcessStarted() {
 checkProcessesNotAlreadyStarted() {
     local startedProcesses=()
     for processName in "${PROCESS_NAMES[@]}"; do
-        if hasProcessStarted "${processName}"; then
+        if isProcessRunning "${processName}"; then
             startedProcesses+=("${processName}")
         fi
     done
@@ -34,109 +34,136 @@ checkProcessesNotAlreadyStarted() {
     fi
 }
 
-assignHttpServerPortRange() {
-    checkParamNum 0 $# || exit 1
+# Starts one of the processes under the 'build/' directory.
+# The process will be called with:
+#     <NAME> <PORT_OPTION> <PORT> <EXTRA_PARAMS>
+#
+# EXPECTED PARAMS:
+#  1 : Process name
+#  2 : Process executable
+#  3 : Environment variable to set the port number into. Empty string if don't care.
+#  4 : Base port in production mode
+#  5 : Number of ports to try in production mode
+#  6 : Base port in dev mode
+#  7 : Number of ports to try in dev mode
+#  8 : Delay after starting the process before checking whether it is still alive
+#  9 : The option to specify the port.
+# 10 : Extra parameters to pass to process. Must not contain Bash variables ; expand them before calling.
+startServerProcess() {
+    checkParamNum 10 $# || exit 1
+    local NAME="${1}"
+    local PROCESS_EXECUTABLE="${2}"
+    local OUTPUT_VARIABLE="${3}"
+    local BASE_PORT_PROD_MODE="${4}"
+    local NUM_TRIES_PROD_MODE="${5}"
+    local BASE_PORT_DEV_MODE="${6}"
+    local NUM_TRIES_DEV_MODE="${7}"
+    local RETRY_DELAY="${8}"
+    local PORT_OPTION="${9}"
+    local EXTRA_PARAMS="${10}"
+
     if "${IS_PROD_MODE}"; then
-        HTTP_SERVER_MIN_PORT=80
+        local MIN_PORT="${BASE_PORT_PROD_MODE}"
+        local MAX_PORT=$(("${MIN_PORT}" + "${NUM_TRIES_PROD_MODE}" - 1))
     else
-        HTTP_SERVER_MIN_PORT=8080
+        local MIN_PORT="${BASE_PORT_DEV_MODE}"
+        local MAX_PORT=$(("${MIN_PORT}" + "${NUM_TRIES_DEV_MODE}" - 1))
     fi
-    HTTP_SERVER_MAX_PORT=$((${HTTP_SERVER_MIN_PORT} + 20))
-}
 
-assignHttpsServerPortRange() {
-    checkParamNum 0 $# || exit 1
-    HTTPS_SERVER_MIN_PORT=7777
-    HTTPS_SERVER_MAX_PORT=$((${HTTPS_SERVER_MIN_PORT} + 20))
-}
+    message $'\nStarting '"${NAME}"$'...\n'
+    local port="${MIN_PORT}"
+    while [ "${port}" != "${MAX_PORT}" ]; do
+        echo $'\n'"Trying port number ${port}"
 
-assignSslDaemonPortRange() {
-    checkParamNum 0 $# || exit 1
-    if "${IS_PROD_MODE}"; then
-        SSL_DAEMON_MIN_PORT=443
-    else
-        SSL_DAEMON_MIN_PORT=4433
-    fi
-    SSL_DAEMON_MAX_PORT=$((${SSL_DAEMON_MIN_PORT} + 20))
-}
+        START_COMMAND="\"${PROCESS_EXECUTABLE}\" \"${PORT_OPTION}\" \"${port}\" ${EXTRA_PARAMS} &"
+        if "${IS_PROD_MODE}" && [ "${port}" -le 1024 ]; then
+            sudo echo -n # The start command is launched in background,
+                         # which means we would start sleeping while the user is typing their password.
+                         # Use a dummy non-background command to make sure the user doesn't have to
+                         # type their password during the retry interval.
 
-assignElevationPlayerPortRange() {
-    checkParamNum 0 $# || exit 1
-    ELEVATION_PLAYER_MIN_PORT=6666
-    ELEVATION_PLAYER_MAX_PORT=$((${ELEVATION_PLAYER_MIN_PORT} + 20))
-}
-
-startHttpServer() {
-    message $'\nStarting HTTP Server...\n'
-    HTTP_SERVER_PORT="${HTTP_SERVER_MIN_PORT}"
-    while [ "${HTTP_SERVER_PORT}" != "${HTTP_SERVER_MAX_PORT}" ]; do
-        echo $'\n'"Trying port number ${HTTP_SERVER_PORT}"
-
-        START_COMMAND="\"./build/${HTTP_SERVER_NAME}/${HTTP_SERVER_NAME}\" --cache-path \"${SERVER_CACHE_PATH}\" --port \"${HTTP_SERVER_PORT}\" &"
-        if "${IS_PROD_MODE}"; then
-            sudo echo -n
             eval "sudo ${START_COMMAND}" # Not quoted intentionally
         else
             eval ${START_COMMAND} # Not quoted intentionally
         fi
-        sleep 0.5
+        sleep "${RETRY_DELAY}"
 
-        if pidof "${HTTP_SERVER_NAME}" >/dev/null; then
+        if isProcessRunning "${NAME}"; then
             break
         else
-            HTTP_SERVER_PORT=$((${HTTP_SERVER_PORT} + 1))
+            port=$((${port} + 1))
         fi
     done
+
+    if [ "${port}" -le "${MAX_PORT}" ]; then
+        eval "${OUTPUT_VARIABLE}"="${port}"
+    else
+        messageError $'\nCould not start '"${NAME}"$'\n'
+    fi
+}
+
+startHttpServer() {
+    checkParamNum 0 $# || exit 1
+    local NAME="${HTTP_SERVER_NAME}"
+    local PROCESS_EXECUTABLE="./build/${HTTP_SERVER_NAME}/${HTTP_SERVER_NAME}"
+    local OUTPUT_VARIABLE="HTTP_SERVER_PORT"
+    local BASE_PORT_PROD_MODE="80"
+    local NUM_TRIES_PROD_MODE="20"
+    local BASE_PORT_DEV_MODE="8080"
+    local NUM_TRIES_DEV_MODE="20"
+    local RETRY_DELAY="0.5"
+    local PORT_OPTION="--port"
+    local EXTRA_PARAMS="--cache-path \"${SERVER_CACHE_PATH}\""
+
+    startServerProcess "${NAME}" "${PROCESS_EXECUTABLE}" "${OUTPUT_VARIABLE}" "${BASE_PORT_PROD_MODE}" "${NUM_TRIES_PROD_MODE}" "${BASE_PORT_DEV_MODE}" "${NUM_TRIES_DEV_MODE}" "${RETRY_DELAY}" "${PORT_OPTION}" "${EXTRA_PARAMS}"
 }
 
 startHttpsServer() {
-    message $'\nStarting HTTPS Server...\n'
-    HTTPS_SERVER_PORT="${HTTPS_SERVER_MIN_PORT}"
-    while [ "${HTTPS_SERVER_PORT}" != "${HTTPS_SERVER_MAX_PORT}" ]; do
-        echo $'\n'"Trying port number ${HTTPS_SERVER_PORT}"
-        "./build/${HTTPS_SERVER_NAME}/${HTTPS_SERVER_NAME}" --cache-path "${SERVER_CACHE_PATH}" --port "${HTTPS_SERVER_PORT}" &
-        sleep 0.5
-        if pidof "${HTTPS_SERVER_NAME}" >/dev/null; then
-            break
-        else
-            HTTPS_SERVER_PORT=$((${HTTPS_SERVER_PORT} + 1))
-        fi
-    done
+    checkParamNum 0 $# || exit 1
+    local NAME="${HTTPS_SERVER_NAME}"
+    local PROCESS_EXECUTABLE="./build/${HTTPS_SERVER_NAME}/${HTTPS_SERVER_NAME}"
+    local OUTPUT_VARIABLE="HTTPS_SERVER_PORT"
+    local BASE_PORT_PROD_MODE="443"
+    local NUM_TRIES_PROD_MODE="20"
+    local BASE_PORT_DEV_MODE="4433"
+    local NUM_TRIES_DEV_MODE="20"
+    local RETRY_DELAY="0.5"
+    local PORT_OPTION="--port"
+    local EXTRA_PARAMS="--cache-path \"${SERVER_CACHE_PATH}\""
+
+    startServerProcess "${NAME}" "${PROCESS_EXECUTABLE}" "${OUTPUT_VARIABLE}" "${BASE_PORT_PROD_MODE}" "${NUM_TRIES_PROD_MODE}" "${BASE_PORT_DEV_MODE}" "${NUM_TRIES_DEV_MODE}" "${RETRY_DELAY}" "${PORT_OPTION}" "${EXTRA_PARAMS}"
 }
 
 startSslDaemon() {
-    message $'\nStarting SSL Daemon...\n'
-    SSL_DAEMON_PORT="${SSL_DAEMON_MIN_PORT}"
-    while [ "${SSL_DAEMON_PORT}" != "${SSL_DAEMON_MAX_PORT}" ]; do
-        echo $'\n'"Trying port number ${SSL_DAEMON_PORT}"
-        START_COMMAND="\"./build/${SSL_DAEMON_NAME}/${SSL_DAEMON_NAME}\" -l \"${SSL_DAEMON_PORT}\" -o \"${HTTPS_SERVER_PORT}\" &"
-        if "${IS_PROD_MODE}"; then
-            sudo echo -n
-            eval "sudo ${START_COMMAND}"
-        else
-            eval ${START_COMMAND}
-        fi
-        sleep 0.5
-        if pidof "${SSL_DAEMON_NAME}" >/dev/null; then
-            break
-        else
-            SSL_DAEMON_PORT=$((${SSL_DAEMON_PORT} + 1))
-        fi
-    done
+    checkParamNum 0 $# || exit 1
+    local NAME="${SSL_DAEMON_NAME}"
+    local PROCESS_EXECUTABLE="./build/${SSL_DAEMON_NAME}/${SSL_DAEMON_NAME}"
+    local OUTPUT_VARIABLE="SSL_DAEMON_PORT"
+    local BASE_PORT_PROD_MODE="7777"
+    local NUM_TRIES_PROD_MODE="20"
+    local BASE_PORT_DEV_MODE="7777"
+    local NUM_TRIES_DEV_MODE="20"
+    local RETRY_DELAY="0.5"
+    local PORT_OPTION="-l"
+    local EXTRA_PARAMS="-o \"${HTTPS_SERVER_PORT}\""
+
+    startServerProcess "${NAME}" "${PROCESS_EXECUTABLE}" "${OUTPUT_VARIABLE}" "${BASE_PORT_PROD_MODE}" "${NUM_TRIES_PROD_MODE}" "${BASE_PORT_DEV_MODE}" "${NUM_TRIES_DEV_MODE}" "${RETRY_DELAY}" "${PORT_OPTION}" "${EXTRA_PARAMS}"
 }
 
 startElevationPlayer() {
-    message $'\nStarting Elevation Player...\n'
-    ELEVATION_PLAYER_PORT="${ELEVATION_PLAYER_MIN_PORT}"
-    while [ "${ELEVATION_PLAYER_PORT}" != "${ELEVATION_PLAYER_MAX_PORT}" ]; do
-        "./build/${ELEVATION_PLAYER_NAME}/${ELEVATION_PLAYER_NAME}" --cache-path "${SERVER_CACHE_PATH}" --port "${ELEVATION_PLAYER_PORT}" &
-        sleep 0.5
-        if pidof "${ELEVATION_PLAYER_NAME}" >/dev/null; then
-            break
-        else
-            ELEVATION_PLAYER_PORT=$((${ELEVATION_PLAYER_PORT} + 1))
-        fi
-    done
+    checkParamNum 0 $# || exit 1
+    local NAME="${ELEVATION_PLAYER_NAME}"
+    local PROCESS_EXECUTABLE="./build/${ELEVATION_PLAYER_NAME}/${ELEVATION_PLAYER_NAME}"
+    local OUTPUT_VARIABLE="ELEVATION_PLAYER_PORT"
+    local BASE_PORT_PROD_MODE="6666"
+    local NUM_TRIES_PROD_MODE="20"
+    local BASE_PORT_DEV_MODE="6666"
+    local NUM_TRIES_DEV_MODE="20"
+    local RETRY_DELAY="0.5"
+    local PORT_OPTION="--port"
+    local EXTRA_PARAMS="--cache-path \"${SERVER_CACHE_PATH}\""
+
+    startServerProcess "${NAME}" "${PROCESS_EXECUTABLE}" "${OUTPUT_VARIABLE}" "${BASE_PORT_PROD_MODE}" "${NUM_TRIES_PROD_MODE}" "${BASE_PORT_DEV_MODE}" "${NUM_TRIES_DEV_MODE}" "${RETRY_DELAY}" "${PORT_OPTION}" "${EXTRA_PARAMS}"
 }
 
 # EXPECTED PARAMS :
@@ -152,14 +179,10 @@ lanunchEverything() {
     mkdir -p "${SERVER_CACHE_PATH}"
     if checkProcessesNotAlreadyStarted; then
         cd "${SERVER_DIR}"
-        assignHttpServerPortRange
-        startHttpServer
-        assignHttpsServerPortRange
-        startHttpsServer
-        assignSslDaemonPortRange
-        startSslDaemon
-        assignElevationPlayerPortRange
         startElevationPlayer
+        startHttpServer
+        startHttpsServer
+        startSslDaemon
         local MESSAGE_STRING=$'\nHTTP Server started on port '"${HTTP_SERVER_PORT}"$',\nHTTPS Server started on port '"${HTTPS_SERVER_PORT}"$',\nSSL Daemon started on port '"${SSL_DAEMON_PORT}"$',\nand '"${ELEVATION_PLAYER_NAME}"$' started on port '"${ELEVATION_PLAYER_PORT}"$'.\nCache path: '"${SERVER_CACHE_PATH}"$'\n\n'
         if ${SHOULD_WAIT}; then
             message "${MESSAGE_STRING}"
